### PR TITLE
feat: if a VimLeave autocmd is set then block

### PR DESCRIPTION
**Pull request by IndianBoy42**
and apply that VimLeave autocmd to the nested nvim

### CODE REVIEW

**Comment by IndianBoy42** [comment]
Context: `fish`'s command to edit the current commandline in place adds an argument of the form `+autocmd VimLeave * ....` to write the cursor position to a file that fish can look at so it leaves the cursor at the same place when we return to the shell. First I saw this was causing errors because there were actually newlines in the middle which `nvim_exec` does not handle nicely. Its fairly well known that to have multiline commands in vimscript you need to precede the continuation lines with `\`, apparently not so when passing commands on the command line but anyway. After investigation I though it would be smart for flatten to assume this means the nested editor should block and add that autocmd to the nested session.

**Comment by willothy** [comment]
Hey, thanks for the PR! I am super busy right now so might not have a lot of time to review, but you've contributed before so I trust your judgement here.

Ping me when this is ready and I'll take a quick look and merge :)

**Comment by IndianBoy42** [comment]
I'll do a bit more test driving and see if anything weird happens

**Comment by willothy** [comment]
Was this working consistently? I'm not sure how I feel about integrating it directly since it's kinda fish-specific, but something like this should definitely be doable via hooks and if it's not I'll see if I can make it doable

**Comment by willothy** [comment]
I am gonna go ahead and close this since I think it's better as a configuration recipe - after thinking it through this should definitely be doable using the `should_block` hook.

**Pull request closed without merging**
